### ISSUE TITLE
Hello World doesn't work.

### ISSUE THREAD

**Issue by rdebath** [jnt0r/brainfuck#1]
This should print "Hello World!"

```bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by jnt0r** [comment]
I will take a look at this the next days.

**Comment by jnt0r** [comment]
I finally got some time to completely rethink the project and got it working.
Do you have some other tests?

**Comment by rdebath** [comment]
The processing works for me.
I have collected some tests at https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b and https://github.com/rdebath/Brainfuck/tree/master/testing

Once I increase the number of cells (and give it a `getchar` input) it seems to run them.
Of course it's far too slow to run some of them in a reasonable time.
